#!/usr/bin/env bash
# vm/phase0/install-sudoers.sh — ensure build-disk.sh runs without a password.
#
# Installs a /etc/sudoers.d drop-in granting NOPASSWD on THIS repo's build-disk.sh
# so it (and an agent) can build the forge disk unattended. If the rule already
# works, this script exits without calling sudo, so there is no password prompt.
# Revert any time with:  ./install-sudoers.sh --uninstall
#
# SECURITY NOTE: build-disk.sh is writable by you, so in practice this grants
# passwordless root to your user. That is the accepted tradeoff you chose.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/config.sh"

DROPIN="/etc/sudoers.d/onix-forge"     # no dot in name — sudo ignores dotted files
TARGET="$ONIX_PHASE0_DIR/build-disk.sh"
USER_NAME="$(id -un)"
MODE="${1:---ensure}"

if [[ "$MODE" == "--uninstall" ]]; then
  log "removing $DROPIN (you'll be prompted for your password)"
  sudo rm -f "$DROPIN"
  log "reverted — build-disk.sh will prompt for a password again"
  exit 0
fi

[[ -f "$TARGET" ]] || die "build-disk.sh not found at $TARGET"

passwordless_rule_works() {
  sudo -n -- "$TARGET" --sudoers-check >/dev/null 2>&1
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
cat > "$tmp" <<EOF
# ONIX forge — passwordless disk builder. Generated by vm/phase0/install-sudoers.sh.
# WARNING: $TARGET is writable by $USER_NAME, so this effectively grants
# passwordless root to $USER_NAME. Accepted tradeoff for agent-driven builds.
# Revert:  $ONIX_PHASE0_DIR/install-sudoers.sh --uninstall
$USER_NAME ALL=(root) NOPASSWD: $TARGET
EOF

log "validating sudoers syntax"
visudo -cf "$tmp" >/dev/null || die "generated sudoers failed syntax check"

if passwordless_rule_works; then
  log "sudoers  : already OK — no password prompt needed"
  log "rule: $USER_NAME NOPASSWD $TARGET"
  exit 0
fi

if [[ "$MODE" == "--check" ]]; then
  warn "sudoers  : missing or stale passwordless build-disk rule"
  warn "fix      : run make phase 001, or run make doctor interactively once"
  exit 1
fi

[[ "$MODE" == "--ensure" ]] || die "unknown option: $MODE"

log "installing $DROPIN (you'll be prompted for your password ONCE if the rule is missing/stale)"
sudo install -m 0440 -o root -g root "$tmp" "$DROPIN"
sudo visudo -cf "$DROPIN" >/dev/null || die "installed drop-in failed validation"

log "done — 'make phase 002' / ./build-disk.sh now run without a password"
log "rule: $USER_NAME NOPASSWD $TARGET"
