#!/usr/bin/env bash
# vm/phase0/install-sudoers.sh — ensure rootful ONIX builders run without a password.
#
# Installs a /etc/sudoers.d drop-in granting NOPASSWD on this repo's rootful
# disk/image builder scripts so they can run unattended. If the rules already
# work, this script exits without calling sudo, so there is no password prompt.
# Revert any time with:  ./install-sudoers.sh --uninstall
#
# SECURITY NOTE: these scripts are writable by you, so in practice this grants
# passwordless root to your user. That is the accepted tradeoff you chose.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/config.sh"

DROPIN="/etc/sudoers.d/onix-forge"     # no dot in name — sudo ignores dotted files
TARGETS=(
  "$ONIX_PHASE0_DIR/build-disk.sh"
  "$ONIX_ROOT/vm/phase2/build-image-skeleton.sh"
)
USER_NAME="$(id -un)"
MODE="${1:---ensure}"

if [[ "$MODE" == "--uninstall" ]]; then
  log "removing $DROPIN (you'll be prompted for your password)"
  sudo rm -f "$DROPIN"
  log "reverted — rootful ONIX builders will prompt for a password again"
  exit 0
fi

for target in "${TARGETS[@]}"; do
  [[ -f "$target" ]] || die "rootful builder not found at $target"
done

passwordless_rule_works() {
  local target
  for target in "${TARGETS[@]}"; do
    sudo -n -- "$target" --sudoers-check >/dev/null 2>&1 || return 1
  done
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
cat > "$tmp" <<EOF
# ONIX — passwordless rootful image builders. Generated by vm/phase0/install-sudoers.sh.
# WARNING: these scripts are writable by $USER_NAME, so this effectively grants
# passwordless root to $USER_NAME. Accepted tradeoff for agent-driven builds.
# Revert:  $ONIX_PHASE0_DIR/install-sudoers.sh --uninstall
$USER_NAME ALL=(root) NOPASSWD: ${TARGETS[0]}, ${TARGETS[1]}
EOF

log "validating sudoers syntax"
visudo -cf "$tmp" >/dev/null || die "generated sudoers failed syntax check"

if passwordless_rule_works; then
  log "sudoers  : already OK — no password prompt needed"
  for target in "${TARGETS[@]}"; do
    log "rule: $USER_NAME NOPASSWD $target"
  done
  exit 0
fi

if [[ "$MODE" == "--check" ]]; then
  warn "sudoers  : missing or stale passwordless rootful builder rules"
  warn "fix      : run make phase 001, or run make doctor interactively once"
  exit 1
fi

[[ "$MODE" == "--ensure" ]] || die "unknown option: $MODE"

log "installing $DROPIN (you'll be prompted for your password ONCE if the rule is missing/stale)"
sudo install -m 0440 -o root -g root "$tmp" "$DROPIN"
sudo visudo -cf "$DROPIN" >/dev/null || die "installed drop-in failed validation"

log "done — 'make phase 002' and 'make phase 205' now run without a password"
for target in "${TARGETS[@]}"; do
  log "rule: $USER_NAME NOPASSWD $target"
done
