#!/usr/bin/env bash
# vm/phase0/install-sudoers.sh — one-time setup so build-disk.sh runs without a password.
#
# Installs a /etc/sudoers.d drop-in granting NOPASSWD on THIS repo's build-disk.sh
# so it (and an agent) can build the forge disk unattended. This is the ONE step
# that prompts for your password. Revert any time with:  ./install-sudoers.sh --uninstall
#
# SECURITY NOTE: build-disk.sh is writable by you, so in practice this grants
# passwordless root to your user. That is the accepted tradeoff you chose.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/config.sh"

DROPIN="/etc/sudoers.d/onix-forge"     # no dot in name — sudo ignores dotted files
TARGET="$ONIX_PHASE0_DIR/build-disk.sh"
USER_NAME="$(id -un)"

if [[ "${1:-}" == "--uninstall" ]]; then
  log "removing $DROPIN (you'll be prompted for your password)"
  sudo rm -f "$DROPIN"
  log "reverted — build-disk.sh will prompt for a password again"
  exit 0
fi

[[ -f "$TARGET" ]] || die "build-disk.sh not found at $TARGET"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
cat > "$tmp" <<EOF
# Onix forge — passwordless disk builder. Generated by vm/phase0/install-sudoers.sh.
# WARNING: $TARGET is writable by $USER_NAME, so this effectively grants
# passwordless root to $USER_NAME. Accepted tradeoff for agent-driven builds.
# Revert:  $ONIX_PHASE0_DIR/install-sudoers.sh --uninstall
$USER_NAME ALL=(root) NOPASSWD: $TARGET
EOF

log "validating sudoers syntax"
visudo -cf "$tmp" >/dev/null || die "generated sudoers failed syntax check"

log "installing $DROPIN (you'll be prompted for your password ONCE)"
sudo install -m 0440 -o root -g root "$tmp" "$DROPIN"
sudo visudo -cf "$DROPIN" >/dev/null || die "installed drop-in failed validation"

log "done — 'make phase 02' / ./build-disk.sh now run without a password"
log "rule: $USER_NAME NOPASSWD $TARGET"
