#!/usr/bin/env bash
# vm/phase5/assemble-local-public-repo.sh — Phase 508 local public repo shape.
#
# Phase 508 builds an AerynOS-inspired public repository layout locally. It does
# not upload anything. The output is meant to be rsync-able to repo.onix-os.com
# later, while remaining testable through file:// today.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ONIX_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
HOST_MOSS="${ONIX_HOST_MOSS:-$ONIX_ROOT/artifacts/host-tools/bin/moss}"

CHANNEL="${ONIX_REPO_CHANNEL:-unstable}"
ARCH="${ONIX_REPO_ARCH:-x86_64}"
PUBLIC_CHANNEL="${ONIX_PUBLIC_REPO_CHANNEL:-main}"
PUBLIC_ROOT="${ONIX_PUBLIC_REPO_DIR:-$ONIX_ROOT/artifacts/onix-public-repo}"
MAIN_DIR="$PUBLIC_ROOT/$PUBLIC_CHANNEL"
STREAM_DIR="$MAIN_DIR/stream/$CHANNEL/$ARCH"
POOL_ROOT="$MAIN_DIR/pool/v0"
WORK_ROOT="${ONIX_PHASE508_WORK_DIR:-$ONIX_ROOT/artifacts/onix-phase5-work/508}"

CANONICAL_REPO_ROOT="${ONIX_CANONICAL_REPO_DIR:-$ONIX_ROOT/artifacts/onix-repo}"
CANONICAL_REPO_DIR="${ONIX_CANONICAL_REPO_SOURCE_DIR:-$CANONICAL_REPO_ROOT/$CHANNEL/$ARCH}"

MODE="assemble"

REQUIRED_PACKAGES=(
  branding
  filesystem
  busybox
  uutils-coreutils
  dropbear
  systemd
  bootstrap-policy
  musl
  linux-pam
  libseccomp
  libgcc-runtime
  rootasrole
  rootasrole-policy
  moss
)

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

log() {
  printf '==> %s\n' "$*"
}

rel() {
  local path="$1"
  case "$path" in
    "$ONIX_ROOT") printf '.' ;;
    "$ONIX_ROOT"/*) printf '%s' "${path#$ONIX_ROOT/}" ;;
    *) printf '%s' "$path" ;;
  esac
}

usage() {
  cat <<'EOF'
usage: assemble-local-public-repo.sh [--assemble|--check]

--assemble  build artifacts/onix-public-repo from the canonical local repo,
            write root-index metadata, and prove Moss can consume it locally
--check     verify an existing local public repo layout and run the same Moss
            consumption proofs

No upload, DNS, or server is touched by this phase.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --assemble) MODE="assemble" ;;
    --check) MODE="check" ;;
    -h|--help) usage; exit 0 ;;
    *) usage >&2; die "unknown argument: $1" ;;
  esac
  shift
done

cd "$ONIX_ROOT"
shopt -s nullglob

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

need_file() {
  [[ -f "$1" ]] || die "missing expected file: $(rel "$1")"
}

need_dir() {
  [[ -d "$1" ]] || die "missing expected directory: $(rel "$1")"
}

need_host_moss() {
  [[ -x "$HOST_MOSS" ]] || die "missing host moss: $(rel "$HOST_MOSS") (run: make phase 202)"
}

select_one_stone() {
  local package="$1"
  local stone
  local name
  local matches=()

  while IFS= read -r stone; do
    name="$("$HOST_MOSS" inspect "$stone" 2>/dev/null |
      awk -F: '$1 ~ /^Name[[:space:]]*$/ { gsub(/^[[:space:]]+|[[:space:]]+$/, "", $2); print $2; exit }')"
    if [[ "$name" == "$package" ]]; then
      matches+=("$stone")
    fi
  done < <(find "$CANONICAL_REPO_DIR" -maxdepth 1 -type f -name '*.stone' \
    ! -name '*dbginfo*' ! -name '*devel*' | sort)

  [[ "${#matches[@]}" -eq 1 ]] \
    || die "expected exactly one $package stone in $(rel "$CANONICAL_REPO_DIR"), found ${#matches[@]}"

  printf '%s\n' "${matches[0]}"
}

pool_bucket_for_package() {
  local package="$1"
  printf '%s\n' "${package:0:1}"
}

pool_dir_for_package() {
  local package="$1"
  printf '%s/%s/%s\n' "$POOL_ROOT" "$(pool_bucket_for_package "$package")" "$package"
}

current_history_from_root_index() {
  local root_index="$MAIN_DIR/moss-root-index.json"
  awk -v channel="$CHANNEL" '
    $0 ~ "\"" channel "\"[[:space:]]*:" { in_stream=1; next }
    in_stream && /"history"[[:space:]]*:/ {
      gsub(/[",]/, "", $2)
      print $2
      exit
    }
  ' "$root_index"
}

write_root_metadata() {
  local history_id="$1"
  local tag_id="snapshot-$history_id"

  cat > "$MAIN_DIR/moss-root-index.json" <<EOF_JSON
{
  "formats": {
    "v0": {}
  },
  "streams": {
    "$CHANNEL": {
      "format": "v0",
      "history": "$history_id",
      "tag": "$tag_id"
    }
  },
  "tags": {
    "$tag_id": {
      "format": "v0",
      "history": "$history_id"
    }
  },
  "history": {
    "$history_id": {
      "format": "v0"
    }
  }
}
EOF_JSON

  if command -v zstd >/dev/null 2>&1; then
    zstd -q -f "$MAIN_DIR/moss-root-index.json" -o "$MAIN_DIR/moss-root-index.json.zst"
  fi

  cat > "$PUBLIC_ROOT/README.txt" <<EOF_README
ONIX local public package repository

This tree is generated by Phase 508.

It is local-only right now. It is shaped so a later phase can upload this
directory to:

  https://repo.onix-os.com/

Current root-index base URI when served publicly:

  https://repo.onix-os.com

Current local root-index base URI:

  file://$PUBLIC_ROOT

Current stream:

  channel=$PUBLIC_CHANNEL
  version=stream/$CHANNEL
  arch=$ARCH
  history=$history_id

Important files:

  $PUBLIC_CHANNEL/moss-root-index.json
  $PUBLIC_CHANNEL/stream/$CHANNEL/$ARCH/stone.index
  $PUBLIC_CHANNEL/history/$history_id/$ARCH/stone.index
  $PUBLIC_CHANNEL/pool/v0/*/*/*.stone
EOF_README

  cat > "$PUBLIC_ROOT/repo.json" <<EOF_JSON
{
  "name": "ONIX",
  "id": "onix",
  "phase": "508",
  "local_root": "$PUBLIC_ROOT",
  "public_base_uri": "https://repo.onix-os.com",
  "moss_root_index": "$PUBLIC_CHANNEL/moss-root-index.json",
  "channel": "$PUBLIC_CHANNEL",
  "stream": "$CHANNEL",
  "architecture": "$ARCH",
  "history": "$history_id",
  "format": "v0"
}
EOF_JSON
}

write_manifest() {
  local history_id="$1"
  local manifest="$MAIN_DIR/MANIFEST.tsv"
  local package stone stone_name pool_dir pool_rel

  printf 'package\tstone\tpool_path\tcanonical_source\n' > "$manifest"
  for package in "${REQUIRED_PACKAGES[@]}"; do
    stone="$(select_one_stone "$package")"
    stone_name="$(basename "$stone")"
    pool_dir="$(pool_dir_for_package "$package")"
    pool_rel="${pool_dir#$MAIN_DIR/}/$stone_name"
    printf '%s\t%s\t%s\t%s\n' \
      "$package" \
      "$stone_name" \
      "$pool_rel" \
      "$(rel "$stone")" >> "$manifest"
  done

  cat > "$MAIN_DIR/history/$history_id/MANIFEST.tsv" <<EOF_MANIFEST
package	stone	pool_path	canonical_source
EOF_MANIFEST
  tail -n +2 "$manifest" >> "$MAIN_DIR/history/$history_id/MANIFEST.tsv"
  cp "$MAIN_DIR/history/$history_id/MANIFEST.tsv" "$MAIN_DIR/stream/$CHANNEL/MANIFEST.tsv"
}

write_checksums() {
  (
    cd "$MAIN_DIR"
    find . -type f ! -name SHA256SUMS | sort |
      while IFS= read -r file; do
        sha256sum "${file#./}"
      done > SHA256SUMS
    sha256sum -c SHA256SUMS >/dev/null
  )
}

check_canonical_input() {
  need_host_moss
  need_file "$CANONICAL_REPO_DIR/stone.index"
  need_file "$CANONICAL_REPO_DIR/SHA256SUMS"
  need_file "$CANONICAL_REPO_DIR/MANIFEST.tsv"

  (
    cd "$CANONICAL_REPO_DIR"
    sha256sum -c SHA256SUMS >/dev/null
  )

  local package stone
  for package in "${REQUIRED_PACKAGES[@]}"; do
    stone="$(select_one_stone "$package")"
    "$HOST_MOSS" inspect --check "$stone" >/dev/null
  done
}

assemble_public_repo() {
  need_cmd awk
  need_cmd cp
  need_cmd date
  need_cmd find
  need_cmd grep
  need_cmd mkdir
  need_cmd rm
  need_cmd sha256sum
  need_cmd sort
  need_cmd tail
  need_host_moss

  log "Phase 508 local public repo input"
  log "source    : $(rel "$CANONICAL_REPO_DIR")"
  log "output    : $(rel "$PUBLIC_ROOT")"
  check_canonical_input

  local history_id parent tmp tmp_main tmp_stream tmp_history package stone stone_name pool_dir
  history_id="${ONIX_PUBLIC_REPO_HISTORY_ID:-$(date -u +%s)}"
  parent="$(dirname "$PUBLIC_ROOT")"
  mkdir -p "$parent"
  tmp="$(mktemp -d "$parent/.onix-public-repo.XXXXXX")"

  cleanup() {
    rm -rf "$tmp"
  }
  trap cleanup EXIT

  tmp_main="$tmp/$PUBLIC_CHANNEL"
  tmp_stream="$tmp_main/stream/$CHANNEL/$ARCH"
  tmp_history="$tmp_main/history/$history_id/$ARCH"

  mkdir -p "$tmp_stream" "$tmp_history" "$tmp_main/pool/v0"

  # The helper variables normally point at the final paths. During assembly we
  # temporarily point them at the atomic staging tree so manifests and indexes
  # contain correct relative paths inside the staged public repository.
  local old_public_root="$PUBLIC_ROOT"
  local old_main_dir="$MAIN_DIR"
  local old_stream_dir="$STREAM_DIR"
  local old_pool_root="$POOL_ROOT"
  PUBLIC_ROOT="$tmp"
  MAIN_DIR="$tmp_main"
  STREAM_DIR="$tmp_stream"
  POOL_ROOT="$tmp_main/pool/v0"

  log "pool      : copying stones into pool/v0"
  for package in "${REQUIRED_PACKAGES[@]}"; do
    stone="$(select_one_stone "$package")"
    stone_name="$(basename "$stone")"
    pool_dir="$(pool_dir_for_package "$package")"
    mkdir -p "$pool_dir"
    cp "$stone" "$pool_dir/$stone_name"
    log "stone     : $(rel "$stone") -> ${pool_dir#$tmp_main/}/$stone_name"
  done

  log "index     : writing history and stream indexes"
  "$HOST_MOSS" index "$POOL_ROOT" -o "$tmp_history" >/dev/null
  cp "$tmp_history/stone.index" "$tmp_stream/stone.index"

  write_manifest "$history_id"
  write_root_metadata "$history_id"
  write_checksums

  PUBLIC_ROOT="$old_public_root"
  MAIN_DIR="$old_main_dir"
  STREAM_DIR="$old_stream_dir"
  POOL_ROOT="$old_pool_root"

  rm -rf "$PUBLIC_ROOT"
  mv "$tmp" "$PUBLIC_ROOT"
  trap - EXIT

  verify_public_repo
  prove_public_repo

  cat <<EOF_SUCCESS

==> success
Phase 508 assembled a local public ONIX repo layout.

local base URI : file://$PUBLIC_ROOT
future base URI: https://repo.onix-os.com
root index     : $(rel "$MAIN_DIR")/moss-root-index.json
stream index   : $(rel "$STREAM_DIR")/stone.index
history index  : $(rel "$MAIN_DIR/history/$history_id/$ARCH")/stone.index
pool           : $(rel "$POOL_ROOT")
EOF_SUCCESS
}

verify_public_repo() {
  need_cmd awk
  need_cmd find
  need_cmd grep
  need_cmd sha256sum
  need_cmd wc
  need_host_moss

  log "verifying : $(rel "$PUBLIC_ROOT")"
  need_file "$PUBLIC_ROOT/README.txt"
  need_file "$PUBLIC_ROOT/repo.json"
  need_file "$MAIN_DIR/moss-root-index.json"
  need_file "$MAIN_DIR/SHA256SUMS"
  need_file "$STREAM_DIR/stone.index"
  need_file "$MAIN_DIR/MANIFEST.tsv"

  local history_id history_dir stone_count package stone
  history_id="$(current_history_from_root_index)"
  [[ -n "$history_id" ]] || die "could not resolve current $CHANNEL history from moss-root-index.json"
  history_dir="$MAIN_DIR/history/$history_id/$ARCH"
  need_file "$history_dir/stone.index"

  (
    cd "$MAIN_DIR"
    sha256sum -c SHA256SUMS >/dev/null
  )

  grep -q '"formats"' "$MAIN_DIR/moss-root-index.json"
  grep -q "\"$CHANNEL\"" "$MAIN_DIR/moss-root-index.json"
  grep -q "\"history\": \"$history_id\"" "$MAIN_DIR/moss-root-index.json"
  grep -q '"format": "v0"' "$MAIN_DIR/moss-root-index.json"
  grep -q '"phase": "508"' "$PUBLIC_ROOT/repo.json"

  if grep -R -n 'O[n]ix' "$PUBLIC_ROOT/README.txt" "$PUBLIC_ROOT/repo.json" "$MAIN_DIR" >/tmp/onix-phase508-bad-brand.txt 2>/dev/null; then
    cat /tmp/onix-phase508-bad-brand.txt >&2
    rm -f /tmp/onix-phase508-bad-brand.txt
    die "forbidden mixed-case branding found in local public repo metadata"
  fi
  rm -f /tmp/onix-phase508-bad-brand.txt

  stone_count="$(find "$POOL_ROOT" -type f -name '*.stone' | wc -l | tr -d '[:space:]')"
  [[ "$stone_count" -eq "${#REQUIRED_PACKAGES[@]}" ]] \
    || die "expected ${#REQUIRED_PACKAGES[@]} stones in pool, found $stone_count"

  for package in "${REQUIRED_PACKAGES[@]}"; do
    stone=("$POOL_ROOT"/*/"$package"/"$package"-*.stone)
    [[ "${#stone[@]}" -eq 1 ]] \
      || die "expected exactly one pooled stone for $package, found ${#stone[@]}"
    "$HOST_MOSS" inspect --check "${stone[0]}" >/dev/null
    grep -q "^$package	" "$MAIN_DIR/MANIFEST.tsv" \
      || die "MANIFEST.tsv missing row for $package"
  done

  log "repo      : layout + checksums + stone integrity OK"
}

prove_one_repo() {
  local proof_name="$1"
  local add_mode="$2"
  local work="$WORK_ROOT/$proof_name"

  rm -rf "$work"
  mkdir -p "$work/moss-root" "$work/moss-cache" "$work/install-target"

  case "$add_mode" in
    root-index)
      "$HOST_MOSS" -D "$work/moss-root" \
        --cache "$work/moss-cache" \
        repo add onix-public \
        "file://$PUBLIC_ROOT" \
        --root-index version=stream/"$CHANNEL" \
        -c "ONIX Phase 508 local public root index" >/dev/null
      ;;
    direct-stream)
      "$HOST_MOSS" -D "$work/moss-root" \
        --cache "$work/moss-cache" \
        repo add onix-public-stream \
        "file://$STREAM_DIR/stone.index" \
        -c "ONIX Phase 508 direct stream index" >/dev/null
      ;;
    *)
      die "internal error: unknown proof mode $add_mode"
      ;;
  esac

  "$HOST_MOSS" -D "$work/moss-root" \
    --cache "$work/moss-cache" \
    repo update >/dev/null

  local install_log="$work/moss-install.log"
  if ! "$HOST_MOSS" -D "$work/moss-root" \
      --cache "$work/moss-cache" \
      -y install --to "$work/install-target" \
      "${REQUIRED_PACKAGES[@]}" >"$install_log" 2>&1; then
    cat "$install_log" >&2
    die "Moss could not install from local public repo proof $proof_name"
  fi

  if grep -q 'duplicate entry:' "$install_log"; then
    cat "$install_log" >&2
    die "local public repo proof $proof_name reported package path ownership collisions"
  fi

  need_file "$work/install-target/usr/lib/os-release"
  need_file "$work/install-target/usr/bin/busybox"
  need_file "$work/install-target/usr/bin/coreutils"
  need_file "$work/install-target/usr/bin/moss"
  need_file "$work/install-target/usr/sbin/dropbear"
  need_file "$work/install-target/usr/lib/systemd/systemd"
  need_file "$work/install-target/usr/lib/ld-musl-x86_64.so.1"
  need_file "$work/install-target/usr/lib/libseccomp.so.2"
  need_file "$work/install-target/usr/bin/dosr"
  need_file "$work/install-target/usr/bin/chsr"
  need_file "$work/install-target/usr/share/defaults/pam.d/sr"
  need_file "$work/install-target/usr/share/defaults/pam.d/dosr"
  need_file "$work/install-target/usr/share/defaults/rootasrole/rootasrole.json"
  need_file "$work/install-target/usr/share/factory/etc/pam.d/sr"
  need_file "$work/install-target/usr/share/factory/etc/pam.d/dosr"
  need_file "$work/install-target/usr/share/factory/etc/security/rootasrole.json"
  need_file "$work/install-target/usr/share/onix/packages/bootstrap-policy.md"
  need_file "$work/install-target/usr/share/onix/packages/rootasrole.md"
  need_file "$work/install-target/usr/share/onix/packages/rootasrole-policy.md"
  need_file "$work/install-target/usr/share/onix/packages/moss.md"

  log "proof     : $proof_name install target OK"
}

prove_public_repo() {
  need_host_moss
  log "proof     : Moss root-index consumption through file://"
  prove_one_repo "root-index" "root-index"
  log "proof     : Moss direct stream-index consumption through file://"
  prove_one_repo "direct-stream" "direct-stream"
}

run_check() {
  log "Phase 508 local public repo layout"
  log "mode      : check"
  verify_public_repo
  prove_public_repo

  cat <<EOF

==> success
Phase 508 local public repo layout is valid and Moss-consumable.

local base URI : file://$PUBLIC_ROOT
future base URI: https://repo.onix-os.com
EOF
}

case "$MODE" in
  assemble) assemble_public_repo ;;
  check) run_check ;;
  *) die "unknown mode: $MODE" ;;
esac
